# Generated by Django 6.0.5 on 2026-05-22 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='matiere',
            name='enseignant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'enseignant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres_enseignees', to=settings.AUTH_USER_MODEL),
        ),
    ]
