# Generated by Django 6.0.5 on 2026-05-15 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to=settings.AUTH_USER_MODEL, verbose_name='Parent / Responsable'),
        ),
    ]
