# Generated by Django 6.0.5 on 2026-05-22 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-created_at']},
        ),
    ]
