# Generated by Django 6.0.4 on 2026-04-26 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('type_paiement', models.CharField(choices=[('scolarite', 'Scolarité'), ('inscription', 'Inscription'), ('cantine', 'Cantine'), ('transport', 'Transport'), ('autre', 'Autre')], default='scolarite', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('numero_recu', models.CharField(max_length=50, unique=True)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recu', to='finance.paiement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
