# Generated by Django 6.0.5 on 2026-05-22 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0002_classe_enseignant_responsable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={'ordering': ['nom']},
        ),
    ]
